version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tt
      POSTGRES_PASSWORD: tt
      POSTGRES_DB: tt
    ports:
      - "5432:5432"
  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://tt:tt@db:5432/tt
    depends_on:
      - db
    ports:
      - "8000:8000"
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "5173:5173"
