version: '3'
services:
  server:
    build:
      context: ..
      dockerfile: infra/server.Dockerfile
    ports:
      - '3000:3000'
  client:
    build:
      context: ..
      dockerfile: infra/client.Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
